# Generated by Django 3.2.25 on 2024-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('activity1', models.CharField(blank=True, max_length=255)),
                ('activity2', models.CharField(blank=True, max_length=255)),
                ('activity3', models.CharField(blank=True, max_length=255)),
                ('adjective', models.CharField(blank=True, max_length=255)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('number1', models.PositiveSmallIntegerField(default=0)),
                ('tvShow', models.CharField(blank=True, max_length=255)),
                ('favAspectTV', models.CharField(blank=True, max_length=255)),
                ('favSnack', models.CharField(blank=True, max_length=255)),
                ('religion', models.CharField(blank=True, max_length=255)),
                ('favBev', models.CharField(blank=True, max_length=255)),
                ('favOpeningLine', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
